DROP DATABASE IF EXISTS `Cities`;
CREATE DATABASE IF NOT EXISTS `Cities` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `Cities`;

DROP TABLE IF EXISTS `City`;
CREATE TABLE IF NOT EXISTS `City` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(35) NOT NULL,
  `Province` char(3) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=4080 ;

INSERT INTO `City` ('ID', `Name`, `Province`) VALUES
    (1, 'Ottawa', 'ON'),
    (2, 'Toronto', 'ON'),
    (3, 'Hamilton', 'ON'),
    (4, 'Kitchener', 'ON'),
    (5, 'Windsor', 'ON'),
    (6, 'London', 'ON'),
    (7, 'Vaughn', 'ON'),
    (8, 'Oshawa', 'ON'),
    (9, 'Brantford', 'ON'),
    (10, 'Niagara', 'ON'),
    (11, 'Barrie', 'ON'),
    (12, 'Brampton', 'ON'),
    (13, 'Burlington', 'ON'),
    (14, 'Cambridge', 'ON'),
    (15, 'Clarence', 'ON'),
    (16, 'Cornwall', 'ON'),
    (17, 'Guelph', 'ON'),
    (18, 'Kingston', 'ON'),
    (19, 'Markham', 'ON'),
    (20, 'Mississauga', 'ON'),
    (21, 'Newmarket', 'ON'),
    (22, 'North Bay', 'ON'),
    (23, 'Oakville', 'ON'),
    (24, 'Peterborough', 'ON'),
    (25, 'Pickering', 'ON'),
    (26, 'Richmond Hill', 'ON'),
    (27, 'Sarnia', 'ON'),
    (28, 'Sault Ste. Marie', 'ON'),
    (29, 'St. Catharines', 'ON'),
    (30, 'St. Thomas', 'ON'),
    (31, 'Stratford', 'ON'),
    (32, 'Sudbury', 'ON'),
    (33, 'Thunder Bay', 'ON'),
    (34, 'Timmins', 'ON'),
    (35, 'Waterloo', 'ON'),
    (36, 'Welland', 'ON'),
    (37, 'Woodstock', 'ON'),
    (38, 'Halifax', 'NS'),
    (39, 'Dartmouth', 'NS'),
    (40, 'Sydney', 'NS'),
    (41, 'Truro', 'NS'),
    (42, 'Kentville', 'NS'),
    (43, 'New Glasgow', 'NS'),
    (44, 'Pictou', 'NS'),
    (45, 'Yarmouth', 'NS'),
    (46, 'Antigonish', 'NS'),
    (47, 'Bridgewater', 'NS'),
    (48, 'Digby', 'NS'),
    (49, 'Guysborough', 'NS'),
    (50, 'Liverpool', 'NS'),
    (51, 'New Minas', 'NS'),
    (52, 'Parrsboro', 'NS'),
    (53, 'Shelburne', 'NS'),
    (54, 'Stellarton', 'NS'),
    (55, 'Stewiacke', 'NS'),
    (56, 'Windsor', 'NS'),
    (57, 'Wolfville', 'NS'),
    (58, 'Charlottetown', 'PE'),
    (59, 'Summerside', 'PE'),
    (60, 'Montague', 'PE'),
    (61, 'Cornwall', 'PE'),
    (62, 'Stratford', 'PE'),
    (63, 'Borden', 'PE'),
    (64, 'Belfast', 'PE'),
    (65, 'Bloomfield', 'PE'),
    (66, 'Cavendish', 'PE'),
    (67, 'Charlottetown', 'PE'),
    (68, 'Cornwall', 'PE'),
    (69, 'Crapaud', 'PE'),
    (70, 'Darnley', 'PE'),
    (71, 'East Royalty', 'PE'),
    (72, 'Elmira', 'PE'),
    (73, 'Elmsdale', 'PE'),
    (74, 'Freetown', 'PE'),
    (75, 'Glenfinnan', 'PE'),
    (76, 'Greenmount', 'PE'),
    (77, 'Hillsborough', 'PE'),
    (78, 'Hunter River', 'PE'),
    (79, 'Kensington', 'PE'),
    (80, 'Kildare', 'PE'),
    (81, 'Moncton', 'NB'),
    (82, 'Saint John', 'NB'),
    (83, 'Fredericton', 'NB'),
    (84, 'Miramichi', 'NB'),
    (85, 'Bathurst', 'NB'),
    (86, 'Campbellton', 'NB'),
    (87, 'Dalhousie', 'NB'),
    (88, 'Edmundston', 'NB'),
    (89, 'Florenceville', 'NB'),
    (90, 'Grand Falls', 'NB'),
    (91, 'Grand Manan', 'NB'),
    (92, 'Hampton', 'NB'),
    (93, 'Kedgwick', 'NB'),
    (94, 'Lameque', 'NB'),
    (95, 'Lancaster', 'NB'),
    (96, 'Memramcook', 'NB'),
    (97, 'Miramichi', 'NB'),
    (98, 'Neguac', 'NB'),
    (99, 'Oromocto', 'NB'),
    (100, 'Quispamsis', 'NB'),
    (101, 'Riverview', 'NB'),
    (102, 'Rogersville', 'NB'),
    (103, 'Rexton', 'NB'),
    (104, 'Rothesay', 'NB'),
    (105, 'Saint Andrews', 'NB'),
    (106, 'Saint John', 'NB'),
    (107, 'Shediac', 'NB'),
    (108, 'Sussex', 'NB'),
    (109, 'Tracadie', 'NB'),
    (110, 'Woodstock', 'NB'),
    (111, 'Saint John', 'NB'),
    (112, 'Fredericton', 'NB'),
    (113, 'Moncton', 'NB'),
    (114, 'Miramichi', 'NB'),
    (115, 'Bathurst', 'NB'),
    (116, 'Campbellton', 'NB'),
    (117, 'Dalhousie', 'NB'),
    (118, 'Edmundston', 'NB'),
    (119, 'Florenceville', 'NB'),
    (120, 'Grand Falls', 'NB'),
    (121, 'Grand Manan', 'NB'),
    (122, 'Hampton', 'NB'),
    (123, 'Vancouver', 'BC'),
    (124, 'Victoria', 'BC'),
    (125, 'Kelowna', 'BC'),
    (126, 'Surrey', 'BC'),
    (127, 'Richmond', 'BC'),
    (128, 'Burnaby', 'BC'),
    (129, 'Langley', 'BC'),
    (130, 'Coquitlam', 'BC'),
    (131, 'Abbotsford', 'BC'),
    (132, 'Port Coquitlam', 'BC'),
    (133, 'Delta', 'BC'),
    (134, 'North Vancouver', 'BC'),
    (135, 'Saanich', 'BC'),
    (136, 'Squamish', 'BC'),
    (137, 'White Rock', 'BC'),
    (138, 'New Westminster', 'BC'),
    (139, 'Maple Ridge', 'BC'),
    (140, 'Penticton', 'BC'),
    (141, 'Nanaimo', 'BC'),
    (142, 'Kamloops', 'BC'),
    (143, 'Chilliwack', 'BC'),
    (144, 'Prince George', 'BC'),
    (145, 'Terrace', 'BC'),
    (146, 'Vernon', 'BC'),
    (147, 'Trail', 'BC'),
    (148, 'Fort St. John', 'BC'),
    (149, 'Prince Rupert', 'BC'),
    (150, 'Quesnel', 'BC'),
    (151, 'Williams Lake', 'BC'),
    (152, 'Smithers', 'BC'),
    (153, 'Dawson Creek', 'BC'),
    (154, 'Kitimat', 'BC'),
    (155, 'Port Alberni', 'BC'),
    (156, 'Powell River', 'BC'),
    (157, 'Port Hardy', 'BC'),
    (158, 'Campbell River', 'BC'),
    (159, 'Nelson', 'BC'),
    (160, 'Merritt', 'BC'),
    (161, 'Penticton', 'BC'),
    (162, 'Kelowna', 'BC'),
    (163, 'Salmon Arm', 'BC'),
    (164, 'Penticton', 'BC'),
    (165, 'Calgary', 'AB'),
    (166, 'Edmonton', 'AB'),
    (167, 'Red Deer', 'AB'),
    (168, 'Lethbridge', 'AB'),
    (169, 'Medicine Hat', 'AB'),
    (170, 'Grande Prairie', 'AB'),
    (171, 'Fort McMurray', 'AB'),
    (172, 'Airdrie', 'AB'),
    (173, 'Okotoks', 'AB'),
    (174, 'Lloydminster', 'AB'),
    (175, 'Leduc', 'AB'),
    (176, 'Spruce Grove', 'AB'),
    (177, 'Stony Plain', 'AB'),
    (178, 'Wetaskiwin', 'AB'),
    (179, 'Strathmore', 'AB'),
    (180, 'Brooks', 'AB'),
    (181, 'Banff', 'AB'),
    (182, 'Canmore', 'AB'),
    (183, 'Drumheller', 'AB'),
    (184, 'High River', 'AB'),
    (185, 'Lacombe', 'AB'),
    (186, 'Medicine Hat', 'AB'),
    (187, 'Olds', 'AB'),
    (188, 'Red Deer', 'AB'),
    (189, 'Rocky Mountain House', 'AB'),
    (190, 'Stettler', 'AB'),
    (191, 'Sylvan Lake', 'AB'),
    (192, 'Three Hills', 'AB'),
    (193, 'Wainwright', 'AB'),
    (194, 'Wetaskiwin', 'AB'),
    (195, 'Whitecourt', 'AB'),
    (196, 'Regina', 'SK'),
    (197, 'Saskatoon', 'SK'),
    (198, 'Prince Albert', 'SK'),
    (199, 'Moose Jaw', 'SK'),
    (200, 'Yorkton', 'SK'),
    (201, 'Swift Current', 'SK'),
    (202, 'North Battleford', 'SK'),
    (203, 'Estevan', 'SK'),
    (204, 'Weyburn', 'SK'),
    (205, 'Melfort', 'SK'),
    (206, 'Melville', 'SK'),
    (207, 'Kindersley', 'SK'),
    (208, 'Meadow Lake', 'SK'),
    (209, 'La Ronge', 'SK'),
    (210, 'Regina', 'SK'),
    (211, 'Saskatoon', 'SK'),
    (212, 'Prince Albert', 'SK'),
    (213, 'Moose Jaw', 'SK'),
    (214, 'Yorkton', 'SK'),
    (215, 'Swift Current', 'SK'),
    (216, 'North Battleford', 'SK'),
    (217, 'Estevan', 'SK'),
    (218, 'Weyburn', 'SK'),
    (219, 'Melfort', 'SK'),
    (220, 'Melville', 'SK'),
    (221, 'Kindersley', 'SK'),
    (222, 'Meadow Lake', 'SK'),
    (223, 'La Ronge', 'SK'),
    (224, 'Winnipeg', 'MB'),
    (225, 'Brandon', 'MB'),
    (226, 'Thompson', 'MB'),
    (227, 'Portage la Prairie', 'MB'),
    (228, 'Steinbach', 'MB'),
    (229, 'Dauphin', 'MB'),
    (230, 'Selkirk', 'MB'),
    (231, 'Morden', 'MB'),
    (232, 'Winkler', 'MB'),
    (233, 'The Pas', 'MB'),
    (234, 'Swan River', 'MB'),
    (235, 'Steinbach', 'MB'),
    (236, 'Thompson', 'MB'),
    (237, 'Winnipeg', 'MB'),
    (238, 'Brandon', 'MB'),
    (239, 'Portage', 'MB'),
    (240, 'Labrador City', 'NL'),
    (241, 'St. John''s', 'NL'),
    (242, 'Corner Brook', 'NL'),
    (243, 'Gander', 'NL'),
    (244, 'Grand Falls-Windsor', 'NL'),
    (245, 'Clarenville', 'NL'),
    (246, 'Mount Pearl', 'NL');
    